image: moss/xelatex:v1.3.1

stages:
    - build

build:
    stage: build
    script:
        - xelatex willianpaixao.tex && rm *aux *log *out
    timeout: 30 minutes
    artifacts:
        paths:
            - willianpaixao.pdf

